apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: earning-demo-api-v2
  name: earning-demo-api-v2
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: earning-demo-api-v2
status:
  loadBalancer: {}
