apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: earning-demo
  name: earning-demo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: earning-demo
    spec:
      containers:
      - image: msorokovsky/dotnetcore-demoapp:1.0.0-earning.demo
        name: earning-demo
        resources: {}
      imagePullSecrets:
      - name: earning-dh-secret
      restartPolicy: Always
status: {}
